version: "3.8"

services:
  db:
    image: mysql:8.3.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_HOST=localhost
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todoitems
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

    ports:
      - "3306:3306"
    # volumes:
    #   - /opt/homebrew/bin/mysql
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: /Users/syedmhdarif/node-rest-api/backend/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=localhost
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todoitems
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

volumes:
  db:
