version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./docker-env

      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todoitems
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/backend
    networks:
      - default

  server:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: ./docker-env
    # environment:
    #   - MYSQL_HOST=mysql
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=123456
    #   - MYSQL_DATABASE=todoitems
    networks:
      - default
    volumes:
      - ./:/var/lib/server

volumes:
  db_data:
